### ISSUE TITLE
Convert all ERB files to HAML

### ISSUE THREAD

**Issue by ephracis** [ephracis/appatite#14]
We need to get pretty. Convert all files of type `html.erb` to `haml`.

**Comment by ephracis** [comment]
- http://www.html2haml.net/
- http://htmltohaml.com/
- https://html2haml.herokuapp.com/

**Comment by cgpacifico** [comment]
I'd like to give this a go - (I'm new to contributing)

**Comment by ephracis** [comment]
Cool!

Here are the general steps on how you contribute:

1. Fork the repository on Github and clone it to your workstation
2. Run the tests, ensuring they all pass
3. Create a feature branch (like `14-haml` where 14 is the issue number)
4. Write new tests (if applicable) and your change
5. Run the tests, ensuring they all pass
6. Submit a Pull Request using Github

Let me know if you need any assistance.
